<a href="https://colab.research.google.com/github/omprateek-non/Heart-disease-app/blob/main/logistic_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd
import numpy as np
import numpy as np
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [68]:
class Logistic_Regression():



    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations



  def fit(self, X, Y):


    self.m, self.n = X.shape




    self.w = np.zeros(self.n)

    self.b = 0

    self.X = X

    self.Y = Y




    for i in range(self.no_of_iterations):
      self.update_weights()



  def update_weights(self):



    Y_hat = 1 / (1 + np.exp( - (self.X.dot(self.w) + self.b ) ))



    dw = (1/self.m)*np.dot(self.X.T, (Y_hat - self.Y))

    db = (1/self.m)*np.sum(Y_hat - self.Y)



    self.w = self.w - self.learning_rate * dw

    self.b = self.b - self.learning_rate * db



  def predict(self, X):

    Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b ) ))
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred

In [69]:
df=pd.read_csv("diabetes.csv")

In [70]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [71]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [72]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [73]:
df.shape

(768, 9)

In [74]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [75]:
scaler= StandardScaler()

In [76]:
df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [77]:
features= df.drop(columns='Outcome', axis=1)
target= df['Outcome']

In [78]:
print(features)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [79]:
scaler=StandardScaler()

In [80]:
standardized_data= scaler.fit_transform(features)

In [81]:
standardized_data= scaler.transform(features)

In [82]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [83]:
feature=standardized_data
target= df['Outcome']

### train split test

In [84]:
X_train,X_test,y_train,y_test = train_test_split(features,target,test_size=0.2,random_state=42)

In [85]:
print(features.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)

In [86]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=2000))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=2000))])

training the model

In [87]:
classifier = Logistic_Regression(learning_rate = 0.01,no_of_iterations=1000)

In [88]:
classifier.fit(X_train,y_train)

In [89]:
x_train_prediction= classifier.predict(X_train)
training_data_accuracy= accuracy_score(x_train_prediction,y_train)

In [90]:

print('accuracy score of the training data:', training_data_accuracy)

accuracy score of the training data: 0.6482084690553745

In [91]:
X_test_prediction =classifier.predict(X_test)
test_data_accuracy= accuracy_score(X_test_prediction,y_test)

In [92]:
print('accuracy score of the testing data :', test_data_accuracy)

accuracy score of the testing data : 0.6558441558441559

In [93]:
model = LogisticRegression(class_weight='balanced', max_iter=1000)

In [94]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [95]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=2000))
])

pipeline.fit(X_train, y_train)

train_pred = pipeline.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, train_pred))

# Test accuracy
test_pred = pipeline.predict(X_test)
print("Test Accuracy:", accuracy_score(y_test, test_pred))

Train Accuracy: 0.7703583061889251
Test Accuracy: 0.7532467532467533

In [97]:
param_grid = {
    'model__C': [0.001, 0.01, 0.1, 1, 10, 100],
    'model__penalty': ['l1', 'l2'],
    'model__solver': ['liblinear']  # 'liblinear' supports both 'l1' and 'l2' penalties
}

print("Hyperparameter grid defined successfully with pipeline prefixes:")
print(param_grid)

Hyperparameter grid defined successfully with pipeline prefixes:
{'model__C': [0.001, 0.01, 0.1, 1, 10, 100], 'model__penalty': ['l1', 'l2'], 'model__solver': ['liblinear']}

In [100]:
input_data = (5,166,72,19,175,25.8,0.587,51)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[ 0.37979288  1.41038486  0.13973176 -0.09071957  0.80559475 -0.79947408
   0.35009487  1.57410227]]
[0]
The person is not diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(